### ISSUE TITLE
Holen's isomorphic-unfetch collide with application's isomorphic-unfetch

### ISSUE THREAD

**Issue by thangngoc89** [tkh44/holen#7]
I'm developing an isomorphic app with Next.js and React.js. 
I have isomorphic-unfetch imported globally like this 

```
import "isomorphic-unfetch`;
```

in every page.

When I import Holen to a page (any page), it will throw an error say that `fetch is undefined` even on browser that have native fetch. 

Removing the import either in Holen's code or in my application's code will "fix" the error.

So I think that Holen should require user to have fetch polyfill globally available instead of importing the polyfill directly.

Thoughts?

**Comment by tkh44** [comment]
Sure put in a PR.
