### ISSUE TITLE
PATCH request method throws prop type warning

### ISSUE THREAD

**Issue by antonydb** [tkh44/holen#9]
Holen currently whitelists `GET`, `POST`, `PUT` and `DELETE`, and throws a prop-type warning when you try to use the [PATCH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) method. While it's only a warning and doesn't restrict you from using the `PATCH` method, it would be nice not to receive the warning.

![image](https://user-images.githubusercontent.com/2289142/33427551-911e925a-d5bd-11e7-9d48-899cf7f8b689.png)

Happy to create a PR :)

**Comment by tkh44** [comment]
Oh wow totally missed that. I'd be happy to accept a PR that added `patch` and `PATCH` to the prop type list.

**Comment by jamesplease** [comment]
This issue can be closed :v:
